import Head from 'next/head'
import React from 'react'

const index = () => {
  return (
    <>
      <Head>
        <title>Design projects</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logo.png" />
      </Head>
      <div className={'h-20'}></div>
      <div className={'w-full'}>
        <div className={'max-w-[1240] mx-auto px-2 py-16'}>
            <p className={'text-xl tracking-widest uppercase text-[#D4AF37] text-center font-bold'}>Projects</p>
            <h2 className={'py-4 text-center'}>Coming soon</h2>
            <div className={'grid md:grid-cols-2 gap-8'}>
                {/* <ExpressStoreAPI title="Express-store-api" backgroundImg={api} projectURL={'/projects/api/express-api'}/> */}
            </div>
        </div>
    </div>
    </>
  )
}

export default index