import Head from 'next/head'
import Link from 'next/link'
import Image from 'next/image'
import React from 'react'
import { useRouter } from 'next/router';
import { BsFillArrowLeftCircleFill } from 'react-icons/bs'

import vue from '../../../../public/assets/skills/vue.png'
import sass from '../../../../public/assets/skills/sass.png'

const Index = () => {
  const router = useRouter();

  return (
    <div>
        <Head>
            <title>Weather-forecast</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/logo.png" />
        </Head>
      
        <div className={'w-full'}>
        <div className={'w-screen h-[25vh] lg:h-[40vh relative]'}>
          <div className={'absolute top-0 left-0 w-full h-[30vh] lg:h-[40vh] bg-[#303030] z-10'}>
            <div className={'absolute top-[70%] max-w-[1240px] w-full left-[50%] right-[50%] translate-x-[-50%] translate-y-[-50%]'}>
              <div onClick={() => router.back()}>
                <div className={'ml-5 mb-5 text-2xl cursor-pointer w-3 h-3 rounded-full hover:text-[#D4AF37]'}>
                  <BsFillArrowLeftCircleFill />
                </div>
              </div>
              <h2 className={'text-[#fff] text-center'}>Executant</h2>
              <div className={'flex justify-center gap-4 mt-5'}>
                <Image src={vue} alt={''} width={'20'} height={'15'}/>
                <Image src={sass} alt={''} width={'20'} height={'15'}/>
              </div>
            </div>
          </div>
        </div>
        <div className={'h-10'}></div>
        <div className={'max-w-[1240px mx-auto p-10 pt-20'}>
          <div className={'col-span-4'}>
            <p>Project</p>
            <h3 className={'mt-2'}>Overview</h3>
            <p className={'mt-2'}>
            The executant application is a cutting-edge software solution tailored 
            for film enthusiasts and professionals alike, revolutionizing the way 
            movies are discovered and accessed. Powered by advanced algorithms and 
            an extensive database of films from various genres and eras, this application 
            allows users to navigate through a vast collection, precisely honing their 
            search based on specific preferences such as release year, director, cast members, or even plot keywords.
            </p>
            <div className={'mt-10'}>
              <Link Link 
                href={'https://github.com/Thabiso-007/executant'}
                className={'px-6 py-3 text-blue-100 no-underline bg-blue-500 rounded hover:bg-blue-600 hover:underline hover:text-blue-200'}
              >
                Source Code
              </Link>
            </div>
            <div className={'mt-10'}>
              <Link Link 
                href={'https://executant.vercel.app/'}
                className={'px-6 py-3 text-blue-100 no-underline bg-blue-500 rounded hover:bg-blue-600 hover:underline hover:text-blue-200'}
              >
                View project
              </Link>
            </div>
          </div>
        </div>
      </div>
    </div>
  )
}

export default Index