import Head from 'next/head'
import Image from 'next/image'
import React from 'react'

import Footer from '../components/footer/Footer'
import touch from '../public/assets/touch.jpg'

const About = () => {
  return (
    <>
      <Head>
        <title>About</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logo.png" />
      </Head>
      <div className={'h-20'}></div>
        <div className={'w-full md:h-screen p-10 flex items-center py-16'}>
          <div className={'max-w-[1240] m-auto md:grid grid-cols-3 gap-8'}>
            <div className={'col-span-2'}>
              <h1 className={'uppercase text-3xl tracking-widest text-[#D4AF37] text-center'}>About Thabiso Hlatshwayo</h1>
              <h2 className={'py-4 text-center'}>Who I am</h2>
              <p className={'py-2 text-gray-100'}>
                After incorporating JavaScript into HTML, I realized the power and versatility of programming. 
                It opened up a whole new world of possibilities for me. I started exploring different frameworks
                and libraries to enhance my software development skills.
              </p>
              <p className={'py-2 text-gray-100'}>
                During my college years, I delved deeper into programming languages like Python and Java. 
                These languages allowed me to build more complex applications and expand my problem-solving 
                abilities. I enjoyed the challenge of creating efficient algorithms and finding elegant solutions 
                to various coding problems.
              </p>
          </div>
          <div className={'w-full h-auto shadow-xl shadow-black rounded-xl flex items-center justify-center p-4 hover:scale-105 ease-in duration-300'}>
            <Image 
              className={'rounded-xl'} 
              src={touch} 
              alt="" 
              width={'320'} 
              height={'320'} 
            />
          </div>
        </div>
      </div>
    </>
  )
}

export default About