import Head from 'next/head'
import Link from 'next/link'
import { 
    AiFillLinkedin,
    AiFillInstagram,
    AiFillGithub,
    AiFillMail,

} from 'react-icons/ai'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logo.png" />
      </Head>
      <div className={'h-20'}></div>
      <div className={'w-full h-fit text-center'}>
        <div className={'max-w-[1240px] w-full h-full mx-auto p-2 flex justify-center items-center'}>
            <div className={''}>
                <p className={'uppercase text-sm tracking-widest text-[#D4AF37]'}>Teams and dreams may coexist.</p>
                <h1 className={'py-4 text-white'}>
                    Hi, I am <span className={'text-[#D4AF37]'}>Thabiso Hlatshwayo</span>
                </h1>
                <h2 className={'py-4 text-white'}>
                    A Full-Stack, Front-end, Back-end Developer 
                </h2>
                <p className={'py-4 text-white max-w-[70%] m-auto'}>
                    As a developer with exceptional and successful projects, 
                    I understand the importance of teamwork in achieving extraordinary results. 
                    Throughout my career, I have witnessed firsthand how collaboration and aligning 
                    individual successes with organizational goals can lead to remarkable achievements.
                </p>
                <p className={'py-4 text-white max-w-[70%] m-auto'}>
                    Teamwork brings together diverse perspectives, skills, and experiences, 
                    creating a synergy that propels us towards our common objective. By pooling our 
                    talents and working towards a shared goal, we can tap into each team member's strengths 
                    and compensate for any weaknesses. This collaborative effort fosters innovation, problem-solving, 
                    and ultimately leads to superior outcomes.
                </p>
                <p className={'py-4 text-white max-w-[70%] m-auto'}>
                    In my journey as a developer, I have actively sought opportunities to collaborate with others. 
                    Whether it was working on complex software development projects or participating in 
                    cross-functional teams, I have consistently strived to contribute my expertise while valuing 
                    the contributions of my teammates. Recognizing that no one person possesses all the answers or
                    skills required for success has been crucial in fostering an environment of trust and mutual 
                    respect within the teams I've worked with. Moreover, teamwork
                </p>
                <div className={'flex items-center justify-between max-w-[400px] m-auto py-4'}>
                    <div className={'rounded-full shadow-lg shadow-gray-900 p-6 cursor-pointer hover:scale-110 ease-in duration-75'}>
                        <Link href={'https://www.instagram.com/thabiso.timzo.dev/'}><AiFillInstagram size={20} /></Link>
                    </div>
                    {/* <div className={'rounded-full shadow-lg shadow-gray-900 p-6 cursor-pointer hover:scale-110 ease-in duration-75'}>
                        <Link href={'https://twitter.com/thabiso_dev'}><AiOutlineTwitter size={20} /></Link>
                    </div> */}
                    <div className={'rounded-full shadow-lg shadow-gray-900 p-6 cursor-pointer hover:scale-110 ease-in duration-75'}>
                        <Link href={'https://www.linkedin.com/in/thabiso-hlatshwayo-8a4079198/'}><AiFillLinkedin size={20} /></Link>
                    </div>
                    <div className={'rounded-full shadow-lg shadow-gray-900 p-6 cursor-pointer hover:scale-110 ease-in duration-75'}>
                        <Link href={'https://github.com/Thabiso-007'}><AiFillGithub size={20}/></Link>
                    </div>
                    <div className={'rounded-full shadow-lg shadow-gray-900 p-6 cursor-pointer hover:scale-110 ease-in duration-75'}>
                        <Link href={'mailto:thabiso.hlatshwayo24@gmail.com'}><AiFillMail size={20}/></Link>
                    </div>
                </div>
            </div>
        </div>
    </div>
    </div>
  )
}
