import React from 'react'
import Head from 'next/head'

import TeckStack from '../components/skills/TeckStack'

const Skills = () => {
  return (
    <>
        <Head>
            <title>Skills</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/logo.png" />
        </Head>
        <div className={'h-40'}></div>
        <div className={'w-full lg:h-screen p-10 mt-20 mb-10'}>
            <div className={'max-w-[1240px] flex flex-col justify-center h-full'}>
                <p className={'tracking-widest uppercase text-[#D4AF37] text-xl text-center font-bold'}>Skills</p>
                <h2 className={'py-7 text-center'}>What I can do</h2>
                <div className={'grid md:grid-cols-2 lg:grid-cols-5 gap-8'}>
                    <TeckStack />
                </div>
            </div>
        </div>
    </>
  )
}

export default Skills